services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=nY2lvLcTJOTBGuYndmTKsOYXHep4Tzr5pvQo7Nmi5M4Oa66V
      - CLIENT_BASE_URL=http://localhost:1221
      - SERVER_BASE_URL=http://localhost:1221
    volumes:
      - ./app-data:/app/app-data
    user: 1000:1000
